### ISSUE TITLE
运行exe的时候报错

### ISSUE THREAD

**Issue by designerMichael** [okcy1016/poetry-desktop#4]
你好：我在liteIDE上build 生成相应的exe文件后，运行报一下错误：
PS D:\Go-Work\src\poetry-desktop> .\poetry-desktop.exe
panic: invalid argument

goroutine 1 [running, locked to thread]:
main.ChkErr(0x7e3080, 0x7dfc18)
        D:/Go-Work/src/poetry-desktop/check_error.go:6 +0x51
main.stopCliApp(0xc042158160)
        D:/Go-Work/src/poetry-desktop/restart_cli_app.go:21 +0x51
main.restartCliApp(0xc042158160, 0xc04242a000, 0xaf, 0xaf)
        D:/Go-Work/src/poetry-desktop/restart_cli_app.go:12 +0x32
main.HandleRPC(0x7e7740, 0xc042004030, 0xc04242a000, 0xaf)
        D:/Go-Work/src/poetry-desktop/main.go:12 +0x60
github.com/zserge/webview._webviewExternalInvokeCallback(0xf27180, 0x6f910d0)
        D:/Go-Work/src/github.com/zserge/webview/webview.go:401 +0x15e
github.com/zserge/webview._cgoexpwrap_e45f56f75773__webviewExternalInvokeCallback(0xf27180, 0x6f910d0)
        _cgo_gotypes.go:318 +0x3c
github.com/zserge/webview._Cfunc_CgoWebViewLoop(0xf27180, 0x1, 0x0)
        _cgo_gotypes.go:165 +0x54
github.com/zserge/webview.(*webview).Loop.func1(0xf27180, 0xc000000001, 0xc000000000)
        D:/Go-Work/src/github.com/zserge/webview/webview.go:310 +0x65
github.com/zserge/webview.(*webview).Loop(0xc042004030, 0x7e7701, 0xc042085e01)
        D:/Go-Work/src/github.com/zserge/webview/webview.go:310 +0x41
github.com/zserge/webview.(*webview).Run(0xc042004030)
        D:/Go-Work/src/github.com/zserge/webview/webview.go:314 +0x37
main.main()
        D:/Go-Work/src/poetry-desktop/main.go:35 +0x114

请问是哪里配置出错了吗

**Comment by okcy1016** [comment]
要自己编译的话。我文档里没有进行说明，不好意思。
具体是：

先进入 poetry_cli 编译命令行版本，再编译 GUI 程序。然后把各种字体，图片，html，css，js， 其他用到的二进制文件（magisk、set_wallpaper） 等等放置到像 release 中安装包安装之后的目录结构与位置。

## 其实要自己编译的话最好就是先安装 release 中的安装包，然后在分别编译命令行版本与 WEB GUI 套壳版本，在分别将他们覆盖安装目录中的 `bin/poetry_cli.exe` 与 `poetry_desktop.exe` 即可。

主要因为这个软件的工作还用到了其他项目（如 magisk）的二进制文件和少量其他依赖（如字体、图片、网页等）。

**Comment by okcy1016** [comment]
你出现错误的原因我也不太清楚，应该是 GUI 程序在调用命令行程序时没有找到目标。
